/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./WebMaster.module.css";

const Card = ({ imageSrc, altText }) => {
  return (
    <section className={styles.card}>
      <img
        loading="lazy"
        src={imageSrc}
        alt={altText}
        className={styles.cardImage}
      />
    </section>
  );
};

export default Card;
